/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arraylist;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaby
 */
public class visual extends javax.swing.JFrame {
    ArrayList<empleado> listaempleado;
    Inventory objeto1;
    DefaultTableModel tabla;
    
    /**
     * Creates new form visual
     */
    public visual() {
        initComponents();
        objeto1 = new Inventory();
        listaempleado = new ArrayList<>();
        tabla = new DefaultTableModel();
        tabla.addColumn("Cédula");
        tabla.addColumn("Nombre");
        tabla.addColumn("Dirección");
        tabla.addColumn("Celular");
        this.tablita.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        name = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        Celular = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        direccionb = new javax.swing.JTextField();
        celularb = new javax.swing.JTextField();
        nameb = new javax.swing.JTextField();
        idb = new javax.swing.JTextField();
        Registrar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Remover = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        limpiar = new javax.swing.JButton();
        crearregistro = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setText("Nombre");

        id.setText("Cédula");

        Celular.setText("Celular");

        Direccion.setText("Dirección");

        idb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbActionPerformed(evt);
            }
        });

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Remover.setText("Remover");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablita);

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        crearregistro.setText("Crear Registro");
        crearregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearregistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(crearregistro))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameb, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idb, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(celularb, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(direccionb, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Registrar)
                        .addGap(18, 18, 18)
                        .addComponent(Modificar)
                        .addGap(11, 11, 11)
                        .addComponent(Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Remover)
                        .addGap(18, 18, 18)
                        .addComponent(Consultar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celularb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registrar)
                    .addComponent(Modificar)
                    .addComponent(Buscar)
                    .addComponent(Remover)
                    .addComponent(Consultar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiar)
                    .addComponent(crearregistro))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        int id = Integer.parseInt(idb.getText());
       String nombre = nameb.getText();
       String direccion = direccionb.getText();
       String celular = celularb.getText();
       empleado aux = new empleado(id,nombre,direccion,celular);
       
       listaempleado.add(aux);
       objeto1.addProduct(aux);
       //Inventory objeto = new Inventory();
       //objeto.grabarLista(listaempleado);
       
       for (int i = 0; i<listaempleado.size();i++){
           System.out.print(listaempleado.get(i).getNombre());
       }
       
       System.out.println("Tamaño :" + listaempleado.size());
    }                                         

    private void buscarrActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarActionPerformed

    private void idbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
int cont=0;
    for(int i =0; i<listaempleado.size();i++){
        if(listaempleado.get(i).getID()== Integer.parseInt(idb.getText())){
            idb.setText(String.valueOf(listaempleado.get(i).getID()));
            nameb.setText(listaempleado.get(i).getNombre());
            direccionb.setText(listaempleado.get(i).getDireccion());
            celularb.setText(listaempleado.get(i).getCelular());
            cont ++;
            break;
            }
        }
    if (cont==0){
        JOptionPane.showMessageDialog(null,"empleado no existe ");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        idb.setText("");
        nameb.setText("");
        direccionb.setText("");
        celularb.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
        
        //limpia
        int filas = tabla.getRowCount();   
        for (int i = 0; i < filas; i++) {
            tabla.removeRow(0);
           
        } 
        //muestra crea un object fila el for va a barrer columna por columna el arraylist  y muestra en la tabla 
        Object fila[] = new Object[tabla.getColumnCount()];
        for (int i=0; i<objeto1.listaempleado.size();i++ ){
            
            fila[0] = objeto1.listaempleado.get(i).getID();
            fila[1] = objeto1.listaempleado.get(i).getNombre();
            fila[2] = objeto1.listaempleado.get(i).getDireccion();
            fila[3] = objeto1.listaempleado.get(i).getCelular();
            
            /******/
            //System.out.println(i);
            
            tabla.addRow(fila);   
        }
       
        tablita.setModel(tabla);
        
        
    
    }//GEN-LAST:event_ConsultarActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Se eliminará el registro","Sí ó No",0);
        if( p == 0)
        {
            objeto1.listaempleado.clear();
            JOptionPane.showMessageDialog(null," El registro se eliminó");
            objeto1.limpiar();
            int filas = tabla.getRowCount(); 
        for (int i = 0; i < filas; i++) {
            tabla.removeRow(0);
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_RemoverActionPerformed

    private void crearregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearregistroActionPerformed
        // TODO add your handling code here:
        File personal;
        String archivo = "empleados.txt";
        PrintWriter write;
        personal = new File(archivo);
        if (!personal.exists()){
            try {
                personal.createNewFile();
                write = new PrintWriter(personal,"utf-8");
                
                write.println("\tEmpleados");
                
                for(int i=0; i<objeto1.listaempleado.size(); i++){
                write.println("");
                write.println("Empleado: "+i);
                write.println("\tNombre: "+objeto1.listaempleado.get(i).getNombre());
                write.println("\tCédula: "+objeto1.listaempleado.get(i).getID());
                write.println("\tDirección: "+objeto1.listaempleado.get(i).getDireccion());
                write.println("\tCelular: "+objeto1.listaempleado.get(i).getCelular());
                write.println("");
                }
                write.close();
                JOptionPane.showMessageDialog(null,"Archivo creado exitosamente");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Error"+e);
            }
        }
        else {
            try {
                write = new PrintWriter(personal,"utf-8");
                
                write.println("\tEmpleados");
                
                for(int i=0; i<objeto1.listaempleado.size(); i++){
                write.println("");
                write.println("Empleado: "+i);
                write.println("\tNombre: "+objeto1.listaempleado.get(i).getNombre());
                write.println("\tCedula: "+objeto1.listaempleado.get(i).getID());
                write.println("\tDireccion: "+objeto1.listaempleado.get(i).getDireccion());
                write.println("\tCelular: "+objeto1.listaempleado.get(i).getCelular());
                write.println("");
                }
                write.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Error"+e);
            }
        }
    }//GEN-LAST:event_crearregistroActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(idb.getText());
        int pos = objeto1.buscar(id);
        if (pos == -1){
        JOptionPane.showMessageDialog(null,"empleado no existe");
        }
        else
        {
                objeto1.listaempleado.remove(pos);
                int IDcedula = Integer.parseInt(idb.getText());
                String direccion = direccionb.getText();
                String celular = celularb.getText();
                String nombre = nameb.getText();
                empleado aux = new empleado(id,nombre,direccion,celular);
                objeto1.listaempleado.add(pos,aux); 
                objeto1.Actualizar();
        }
    }//GEN-LAST:event_ModificarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Celular;
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel ID1;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Remover;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscar1;
    private javax.swing.JLabel celular;
    private javax.swing.JLabel celular1;
    private javax.swing.JTextField celularb;
    private javax.swing.JButton crearregistro;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel direccion1;
    private javax.swing.JTextField direccionb;
    private javax.swing.JLabel id;
    private javax.swing.JTextField idb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameb;
    private javax.swing.JButton registrar;
    private javax.swing.JButton registrar1;
    private javax.swing.JButton remover;
    private javax.swing.JButton remover1;
    private javax.swing.JTable tablita;
    // End of variables declaration//GEN-END:variables
}
